/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.SwingUtilities;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author acwf580
 */
public class ProduceInvoiceOrReminderStep2 extends javax.swing.JPanel {

    ProduceInvoiceOrReminderStep1 PIOR = new ProduceInvoiceOrReminderStep1(false);
    ProduceInvoice PI = new ProduceInvoice("PIOR");
    CashPayment cash = new CashPayment();
    CardPayment card = new CardPayment();
    /**
     * Creates new form ProduceInvoiceOrReminder
     */
    public ProduceInvoiceOrReminderStep2() {
        System.out.println("Test4: "+PIOR.getRegNo());
        initComponents();
        System.out.println("Test5: "+PIOR.getRegNo());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logOut4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        invoiceButton = new javax.swing.JButton();
        reminder1Button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        reminder2Button = new javax.swing.JButton();
        reminder3Button = new javax.swing.JButton();
        motReminderButton = new javax.swing.JButton();

        logOut4.setText("Log Out");
        logOut4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setText("GARITS");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.jpg"))); // NOI18N

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        invoiceButton.setText("Invoice");
        invoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceButtonActionPerformed(evt);
            }
        });

        reminder1Button.setText("1st Invoice Reminder");
        reminder1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reminder1ButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("Produce");

        reminder2Button.setText("2nd Invoice Reminder");
        reminder2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reminder2ButtonActionPerformed(evt);
            }
        });

        reminder3Button.setText("3rd Invoice Reminder");
        reminder3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reminder3ButtonActionPerformed(evt);
            }
        });

        motReminderButton.setText("MoT Reminder");
        motReminderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motReminderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(invoiceButton)
                                .addGap(18, 18, 18)
                                .addComponent(reminder1Button)
                                .addGap(18, 18, 18)
                                .addComponent(reminder2Button)
                                .addGap(18, 18, 18)
                                .addComponent(reminder3Button)
                                .addGap(27, 27, 27)
                                .addComponent(motReminderButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addComponent(jLabel5)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(132, 132, 132)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reminder1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reminder2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reminder3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motReminderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceButtonActionPerformed
        // TODO add your handling code here:
        Homepage homepage = (Homepage) SwingUtilities.getWindowAncestor(this);
        homepage.setContentPane(new ProduceInvoice("PIOR"));
        homepage.setVisible(true);
        
    }//GEN-LAST:event_invoiceButtonActionPerformed

    private void reminder1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reminder1ButtonActionPerformed
        // TODO add your handling code here:
        Homepage homepage = (Homepage) SwingUtilities.getWindowAncestor(this);
        homepage.setContentPane(new ProduceReminder1());
        homepage.setVisible(true);
        
    }//GEN-LAST:event_reminder1ButtonActionPerformed

    private void reminder2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reminder2ButtonActionPerformed
        // TODO add your handling code here:
        Homepage homepage = (Homepage) SwingUtilities.getWindowAncestor(this);
        homepage.setContentPane(new ProduceReminder2());
        homepage.setVisible(true);
    }//GEN-LAST:event_reminder2ButtonActionPerformed

    private void reminder3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reminder3ButtonActionPerformed
        // TODO add your handling code here:
        Homepage homepage = (Homepage) SwingUtilities.getWindowAncestor(this);
        homepage.setContentPane(new ProduceReminder3());
        homepage.setVisible(true);
    }//GEN-LAST:event_reminder3ButtonActionPerformed

    private void motReminderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motReminderButtonActionPerformed
        // TODO add your handling code here:
        Homepage homepage = (Homepage) SwingUtilities.getWindowAncestor(this);
        homepage.setContentPane(new MOTReminder());
        homepage.setVisible(true);
    }//GEN-LAST:event_motReminderButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Homepage homepage = (Homepage) SwingUtilities.getWindowAncestor(this);
        homepage.setContentPane(new ProduceInvoiceOrReminderStep1(true));
        homepage.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logOut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut4ActionPerformed
        // TODO add your handling code here:
        InputStream music;
        try{
            music = new FileInputStream(new File("goodbye.wav"));
            AudioStream audio = new AudioStream(music);
            AudioPlayer.player.start(audio);

        }catch(Exception e){

            System.out.println(e.getMessage());
        }
        Homepage homepage = (Homepage) SwingUtilities.getWindowAncestor(this);
        homepage.dispose();

        new Homepage().setVisible(true);
    }//GEN-LAST:event_logOut4ActionPerformed
/*
    public void latePayAlert(){
        if((PI.getDate().getMonth().equals(LocalDate.now().getMonth()) ) 
           | (PI.getDate().plusMonths(2).equals(LocalDate.now()) && cash.hasBeenPaid() == false)
           | (PI.getDate().plusMonths(3).equals(LocalDate.now()) && cash.hasBeenPaid() == false)
           | (PI.getDate().plusMonths(1).equals(LocalDate.now()) && card.hasBeenPaid() == false)
           | (PI.getDate().plusMonths(2).equals(LocalDate.now()) && card.hasBeenPaid() == false)
           | (PI.getDate().plusMonths(3).equals(LocalDate.now()) && card.hasBeenPaid() == false)){
            JOptionPane.showMessageDialog(null, "PAYMENT IS OVERDUE!");
        }
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton invoiceButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton logOut4;
    private javax.swing.JButton motReminderButton;
    private javax.swing.JButton reminder1Button;
    private javax.swing.JButton reminder2Button;
    private javax.swing.JButton reminder3Button;
    // End of variables declaration//GEN-END:variables
}
